name: math
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  google_fonts:
  cupertino_icons: ^1.0.8

  #Dependencia de video_player
  #video_player: ^2.4.5
  #youtube_player_flutter: ^9.1.1
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo1.png
    - assets/logo_sinFondo.png
    - assets/bien.png
    - assets/mal.png
